eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
notificationservice:
  url: http://localhost:8050/
resilience4j:
  circuitbreaker:
    instances:
      customer_service:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 5s
server:
  port: 0
spring:
  jpa:
    open-in-view: false
